// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bifsslngdjrcxawbcend.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpZnNzbG5nZGpyY3hhd2JjZW5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NTY3NDIsImV4cCI6MjA2MzUzMjc0Mn0.-KsPdjvPXGm9Xgq4Stgi58z1YW7zFEaggec_fSI02PM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);